### ISSUE TITLE
предложения и протесты

### ISSUE THREAD

**Issue by omalakhovskaya** [bdemeshev/r_manual_book#6]
1/ Мне больше нравиться, не "шалунишка", а что-то вроде "признайся, ты давно хотел пошалить...".
С шалунишкой у меня неправильные ассоциации 

2/ Когда ты называешь Эйлера и Клеро Лёнькой и Алешкой, то формируешь у читателя патриотизм на пустом месте, он начинает думать, что они были русскими.

3/ Я протестую. Ты не включил Матлаб в число китов. О существовании Юли знаешь ты и Саржент. Большинство серьезных работ использует Матлаб. Это три бесплатных кита (китёнка?), не более того!

**Comment by bdemeshev** [comment]
1. Я подумаю!
2. Пусть будет - математика интернациональна.
3. Это не кит, это Титаник :)

**Comment by omalakhovskaya** [comment]
1. Я бы увидела книжку на полке, открыла ее, прочитала "Лёнька Эйлер"  и
   поставила бы на место. Не купила бы. Где уважение к гениям? :)
2. Ага, ну жди утопления! Он нас с тобой переживет.
   По-моему, ты просто назвал китами те программы, которые ты сам любишь.
   Просто самонадеянность безграничная проявляется! :)

**Comment by bdemeshev** [comment]
2. да, я понимаю, что с неформальным стилем может быть перебор
3. гугл видит общий [тренд](https://www.google.co.uk/trends/explore?date=all&q=%2Fm%2F053_x)

**Comment by omalakhovskaya** [comment]
А этот тренд о чем говорит?

https://www.google.co.uk/trends/explore?date=all&geo=CN&q=%2Fm%2F053_x

**Comment by bdemeshev** [comment]
что китайцы ещё качают пиратский матлаб :)
